#number guessing game
import random
a= random.randint(1,10)
print("You have only 3 chance")
score=0
print("Guess the number generated by computer between the range 1 to 10")
for chance in range(3):
    ur=int(input("enter a number  :  "))
    if ur==a:
        print("You won the game ")
        score+=1
        print("Your score is  : ",score)
        break
        #print("Wrong answer")
if score==0:
      print("OOPS!!!! try next time")
      print(a,"is the number")
      print("Your score is  : ",score)